using System;
using System.Collections.Generic;
using System.Text;

namespace PFound.ECS
{
    /// <summary>
    /// Turns a system type list into the C# source of a static registry that registers each
    /// system with <c>new T()</c> — no runtime reflection, IL2CPP/AOT-safe. Pure and
    /// deterministic (same input ⇒ identical output) so it is testable without Unity and its
    /// output diffs cleanly in version control.
    /// </summary>
    public static class SystemRegistryEmitter
    {
        /// <summary>
        /// Emits a <paramref name="className"/> static class in <paramref name="namespace"/> exposing
        /// <c>Type[] SystemTypes</c> and <c>void Register(World)</c>. <paramref name="systems"/> is
        /// emitted in the given order (callers pass <see cref="SystemDiscovery.SelectSystems"/> output).
        /// </summary>
        public static string Emit(string @namespace, string className, IReadOnlyList<Type> systems)
        {
            if (string.IsNullOrEmpty(@namespace)) throw new ArgumentException("namespace required", nameof(@namespace));
            if (string.IsNullOrEmpty(className)) throw new ArgumentException("className required", nameof(className));
            if (systems == null) throw new ArgumentNullException(nameof(systems));

            var sb = new StringBuilder();
            sb.Append("// <auto-generated>\n");
            sb.Append("//     Generated by PFound.ECS SystemRegistryGenerator. Do not edit by hand;\n");
            sb.Append("//     re-run Tools > PFound ECS > Regenerate System Registry instead.\n");
            sb.Append("// </auto-generated>\n");
            sb.Append("using PFound.ECS;\n\n");
            sb.Append("namespace ").Append(@namespace).Append("\n{\n");
            sb.Append("    /// <summary>Compile-time system registry — the reflection-free discovery path.</summary>\n");
            sb.Append("    public static class ").Append(className).Append("\n    {\n");

            sb.Append("        /// <summary>Every registrable system type, in deterministic order.</summary>\n");
            sb.Append("        public static readonly System.Type[] SystemTypes =");
            if (systems.Count == 0)
            {
                sb.Append(" System.Array.Empty<System.Type>();\n\n");
            }
            else
            {
                sb.Append("\n        {\n");
                foreach (var t in systems)
                    sb.Append("            typeof(").Append(TypeRef(t)).Append("),\n");
                sb.Append("        };\n\n");
            }

            sb.Append("        /// <summary>Instantiates and registers every system on <paramref name=\"world\"/>.</summary>\n");
            sb.Append("        public static void Register(World world)\n        {\n");
            foreach (var t in systems)
                sb.Append("            world.RegisterSystem(new ").Append(TypeRef(t)).Append("());\n");
            sb.Append("        }\n");

            sb.Append("    }\n}\n");
            return sb.ToString();
        }

        // Fully-qualified, nested types as '.' so the name is valid in `new`/`typeof` without usings.
        private static string TypeRef(Type t)
        {
            if (t == null) throw new ArgumentNullException(nameof(t));
            return t.FullName.Replace('+', '.');
        }
    }
}
