// <auto-generated>
//     Generated by PFound.ECS SystemRegistryGenerator. Do not edit by hand;
//     re-run Tools > PFound ECS > Regenerate System Registry instead.
// </auto-generated>
using PFound.ECS;

namespace PFound.ECS.Generated
{
    /// <summary>Compile-time system registry — the reflection-free discovery path.</summary>
    public static class SystemRegistry
    {
        /// <summary>Every registrable system type, in deterministic order.</summary>
        public static readonly System.Type[] SystemTypes =
        {
            typeof(PFound.ECS.Tests.Registry.ExampleInputSystem),
            typeof(PFound.ECS.Tests.Registry.ExampleMovementSystem),
        };

        /// <summary>Instantiates and registers every system on <paramref name="world"/>.</summary>
        public static void Register(World world)
        {
            world.RegisterSystem(new PFound.ECS.Tests.Registry.ExampleInputSystem());
            world.RegisterSystem(new PFound.ECS.Tests.Registry.ExampleMovementSystem());
        }
    }
}
