// <auto-generated>
//     Generated by PFound.ECS SystemRegistryGenerator. Do not edit by hand;
//     re-run Tools > PFound ECS > Regenerate System Registry instead.
// </auto-generated>
using PFound.ECS;

namespace PFound.ECS.Samples.Generated
{
    /// <summary>Compile-time system registry — the reflection-free discovery path.</summary>
    public static class SystemRegistry
    {
        /// <summary>Every registrable system type, in deterministic order.</summary>
        public static readonly System.Type[] SystemTypes =
        {
            typeof(PFound.ECS.Samples.CameraModule.CameraFollowSystem),
            typeof(PFound.ECS.Samples.ParticleModule.ParticleControlSystem),
            typeof(PFound.ECS.Samples.RenderModule.ColorPulseSystem),
            typeof(PFound.ECS.Samples.TransformModule.SpinSystem),
            typeof(PFound.ECS.Samples.TransformModule.TransformSyncSystem),
        };

        /// <summary>Instantiates and registers every system on <paramref name="world"/>.</summary>
        public static void Register(World world)
        {
            world.RegisterSystem(new PFound.ECS.Samples.CameraModule.CameraFollowSystem());
            world.RegisterSystem(new PFound.ECS.Samples.ParticleModule.ParticleControlSystem());
            world.RegisterSystem(new PFound.ECS.Samples.RenderModule.ColorPulseSystem());
            world.RegisterSystem(new PFound.ECS.Samples.TransformModule.SpinSystem());
            world.RegisterSystem(new PFound.ECS.Samples.TransformModule.TransformSyncSystem());
        }
    }
}
